/*
 * File: app/view/LoginForm.js
 *
 * This file was generated by Sencha Architect version 4.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LoginRegister.view.LoginForm', {
    extend: 'Ext.window.Window',
    alias: 'widget.loginform',

    requires: [
        'LoginRegister.view.LoginFormViewModel',
        'LoginRegister.view.LoginFormViewController',
        'Ext.form.Panel',
        'Ext.button.Button',
        'Ext.form.field.Number',
        'Ext.form.field.Date',
        'Ext.form.CheckboxGroup',
        'Ext.form.field.Checkbox',
        'Ext.calendar.panel.Day',
        'Ext.calendar.panel.Month'
    ],

    controller: 'loginform',
    viewModel: {
        type: 'loginform'
    },
    modal: true,
    height: 400,
    shrinkWrap: 3,
    manageHeight: false,
    title: 'Login',

    items: [
        {
            xtype: 'form',
            bodyPadding: 20,
            items: [
                {
                    xtype: 'textfield',
                    margin: '0 0 20 0',
                    fieldLabel: 'Username',
                    labelAlign: 'right',
                    msgTarget: 'title',
                    name: 'identity',
                    allowBlank: false,
                    blankText: 'Enter your Username.',
                    regexText: 'Enter your username.'
                },
                {
                    xtype: 'textfield',
                    margin: '0 0 10 0',
                    fieldLabel: 'Password',
                    labelAlign: 'right',
                    msgTarget: 'title',
                    name: 'password',
                    inputType: 'password',
                    allowBlank: false,
                    blankText: 'Enter your password.',
                    listeners: {
                        render: 'onTextfieldRender'
                    }
                },
                {
                    xtype: 'button',
                    formBind: true,
                    margin: '0 15 0 0',
                    scale: 'medium',
                    text: 'Login',
                    listeners: {
                        click: 'onLoginButtonClick'
                    }
                },
                {
                    xtype: 'numberfield',
                    anchor: '100%',
                    fieldLabel: 'Label'
                },
                {
                    xtype: 'datefield',
                    fieldLabel: 'Label'
                },
                {
                    xtype: 'datefield',
                    fieldLabel: 'Label'
                },
                {
                    xtype: 'checkboxgroup',
                    fieldLabel: 'Label',
                    items: [
                        {
                            xtype: 'checkboxfield',
                            boxLabel: 'Box Label'
                        },
                        {
                            xtype: 'checkboxfield',
                            boxLabel: 'Box Label'
                        }
                    ]
                }
            ],
            views: {
                day: {
                    xtype: 'calendar-day',
                    label: 'Day'
                },
                month: {
                    xtype: 'calendar-month',
                    label: 'Month'
                }
            }
        }
    ]

});